version: '3.7'

services:
    roadrunner:
        build:
            context: .
            dockerfile: ./containers/roadrunner/Dockerfile
        container_name: roadrunner
        ports:
            - 8080:8080
        volumes:
            - ${WORKER_SRC}:/var/www/app
    
    composer:
        build:
            context: ./containers/php
            dockerfile: php-composer.docker
        tty: true
        command: install
        volumes:
            - ${WORKER_SRC}:/app